version: "3"
services:
  chate2e-api:
    container_name: chate2e-api
    #build: .
    image: ghcr.io/boryssey/e2e-chat-backend:main
    env_file: .env
    ports: 
      - "3000:3000"
    networks: 
      - chate2e
    depends_on:
      - chate2e-db
  
  chate2e-db:
    container_name: chate2e-db
    restart: unless-stopped
    env_file: .env
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - chate2e-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - chate2e

  watchtower:
    container_name: chate2e-watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ~/.docker/config.json:/config.json

    command: --interval 30 chate2e-api

volumes:
  chate2e-data:

networks:
  chate2e:
    name: chate2e
    driver: bridge
